In [81]:
import pandas as pd

In [308]:
df = pd.read_csv('data/perfumes_df.csv')

In [309]:
df.shape

(4485, 15)

In [310]:
df.head()

,perfume_name,designer,group,main_accords,all_notes,top_notes,middle_notes,base_notes,longevity,sillage,synopsis,overall_rating,total_num_voters,opinions,purchases
0,Eau de Soleil Blanc Tom Ford for women and men,Tom Ford,Oriental Floral,"[('citrus', ' 130'), ('white floral', ' 119'),...","['Bitter Orange', 'Bergamot', 'Petitgrain', 'C...","['Bitter Orange', 'Bergamot', 'Petitgrain', 'C...","['Tunisian Orange Blossom', 'Jasmine', 'Tubero...","['Coconut', 'Amber', 'Vanilla', 'Tonka Bean', ...","[('poor', '14'), ('weak', '25'), ('moderate', ...","[('soft', '47'), ('moderate', '34'), ('heavy',...",Eau De Soleil Blanc\n \n ...,4.11,410.0,"[('Love', ' 100'), ('Like', ' 74'), ('DislikeW...","[('I have it', '279'), ('I had it', '40'), ('I..."
1,Narciso Rodriguez for Him Narciso Rodriguez fo...,Narciso Rodriguez,Aromatic Fougere,"[('ozonic', ' 130'), ('musky', ' 120'), ('patc...","['Violet Leaf', 'Patchouli', 'Amber', 'Musk']",NaN,NaN,NaN,"[('poor', '33'), ('weak', '39'), ('moderate', ...","[('soft', '87'), ('moderate', '285'), ('heavy'...",The male fragrance from Narciso Rodriguez and ...,3.94,2311.0,"[('Love', ' 100'), ('Like', ' 70'), ('DislikeW...","[('I have it', '2021'), ('I had it', '638'), (..."
2,Dent de Lait Serge Lutens for women and men,Serge Lutens,Floral Woody Musk,"[('almond', ' 130'), ('metallic', ' 113'), ('f...","['Milk', 'Metallic notes', 'Incense', 'Heliotr...",NaN,NaN,NaN,"[('poor', '2'), ('weak', '7'), ('moderate', '1...","[('soft', '11'), ('moderate', '26'), ('heavy',...",Dent de Lait\n \n\n b...,2.65,123.0,"[('Love', ' 44'), ('Like', ' 45'), ('DislikeWi...","[('I have it', '50'), ('I had it', '12'), ('I ..."
3,The Lotus Flower and the King Dragon By Kilian...,By Kilian,NaN,NaN,[],NaN,NaN,NaN,"[('poor', '5'), ('weak', '1'), ('moderate', '0...","[('soft', '3'), ('moderate', '1'), ('heavy', '...",The Lotus Flower and the King Dragon\n ...,1.67,9.0,"[('Love', ' 20'), ('Like', ' 1'), ('DislikeWin...","[('I want it', '11')]"
4,Les Secrets de Sophie Guerlain for women,Guerlain,Oriental Floral,"[('white floral', ' 130'), ('citrus', ' 124'),...","['Tunisian Neroli', 'Petitgrain', 'Bergamot', ...","['Tunisian Neroli', 'Petitgrain', 'Bergamot', ...","['Orange Blossom', 'Jasmine', 'Violet Leaf', '...","['Tonka Bean', 'Vanilla', 'Incense', 'White Mu...","[('poor', '1'), ('weak', '0'), ('moderate', '0...","[('soft', '2'), ('moderate', '2'), ('heavy', '...",A new perfume by the house of\n \n...,4.44,47.0,"[('Love', ' 100'), ('Like', ' 50'), ('DislikeW...","[('I have it', '21'), ('I had it', '6'), ('I w..."

In [239]:
df.isnull().sum()

perfume_name           0
designer               0
group                115
main_accords          40
all_notes              0
top_notes           1067
middle_notes        1067
base_notes          1067
longevity              0
sillage                0
synopsis              37
overall_rating        34
total_num_voters      34
opinions             216
purchases            216
dtype: int64

In [240]:
df.dtypes

perfume_name         object
designer             object
group                object
main_accords         object
all_notes            object
top_notes            object
middle_notes         object
base_notes           object
longevity            object
sillage              object
synopsis             object
overall_rating      float64
total_num_voters    float64
opinions             object
purchases            object
dtype: object

In [241]:
print(min(df['total_num_voters']))
print(min(df['overall_rating']))

1.0
1.0

## <span style='color:navy'> Filling the Null Values </span>
To fill the nulls in the data frame, you can't do it on a subset. Instead we use the `value` arguments in `.fillna()`, with a dictionary of columns of the data frame, and the values I want to fill their nulls with. This is used to customize how I wish to fill the null values in each column of the data frame. <br />
Since I want to fill all the words (objects) columns with 'not found', and the float ones with -1, I will make a dictionary with these criteria. <br />
The following cell is how I do it.

In [242]:
# make a list of the object columns and the float columns in the data frame
object_columns = list(df.select_dtypes(include = 'object', exclude='float64').columns)
float_columns = list(df.select_dtypes(include = 'float64'))

# create a list of the same two word, of the same length of object_columns list
fill_not_found = ['not found'] * len(object_columns)

# create a dictionary of the zipped lists
values_to_fill = {key: value for key, value in zip(object_columns, fill_not_found)}

# add new keys and values to the dictionary values_to_fill
for c in float_columns:
    values_to_fill[c] = -1

# now fill in the nulls
df.fillna(value = values_to_fill, inplace = True)

In [243]:
df.isnull().sum()

perfume_name        0
designer            0
group               0
main_accords        0
all_notes           0
top_notes           0
middle_notes        0
base_notes          0
longevity           0
sillage             0
synopsis            0
overall_rating      0
total_num_voters    0
opinions            0
purchases           0
dtype: int64

## <span style='color:navy'> Cleaning the data frame

In [244]:
df.shape

(4485, 15)

In [245]:
# dropping duplicates
df.drop_duplicates('perfume_name', keep = 'first', inplace = True) # cannot be placed inside clean_up_perfume_df function!!
df.reset_index(level = 0, drop = True, inplace=True)

In [246]:
df.shape

(4478, 15)

In [247]:
def clean_up_perfume_df(df):
    """
    Specifically written for the perfume/characteristcs df. 
    Adds the gender column
    Extracts values of longivity, sillage, purchases, opinions. Adds them to the df, and drops the original columns.  
    
    Parameters:
    -----------
    df is the name of the df you want fixed. MUST BE perfume characteristics only! of the format I prepared earlier using
    fragrantica_library.py 
    
    """

    # adding the gender column 
    df['gender'] = df['perfume_name'].map(lambda x: x.split('for')[1].strip())
    
    # creating longivity columns, and append them to a list. Notice that not every row contains everything. and it's all 
    # stored as a list of tuples, were it was saved as a string, not as list of tuples. 
    import re
    
    longvity_list = []
    for k in range(5):
        longvity_list.append(df['longevity'].map(lambda x: int( re.sub("[^0-9]", "", x.split('),')[k]) )))
    
    # creating a dataframe of the new list of longvity lists
    longvity_df = pd.DataFrame(longvity_list).T
    longvity_df.columns = [f'longvity_{i}' for i in ['poor', 'weak', 'moderate', 'long_lasting', 'very_long_lasting']]
    
    # adding the new columns to the original df, while dropping duplicate column at the same time
    df = pd.concat([df.drop(['longevity'], axis = 1), longvity_df], axis = 1, sort = False)
    
    # doing the same for sillage
    sillage_list = []
    for k in range(4):
        sillage_list.append(df['sillage'].map(lambda x: int( re.sub("[^0-9]","" ,x.split(')')[k]) )))

    sillage_df = pd.DataFrame(sillage_list).T
    sillage_df.columns = [f"sillage_{i}" for i in ['soft', 'moderate', 'heavy','enormous']]

    df = pd.concat([df.drop(['sillage'], axis = 1), sillage_df], axis = 1, sort = False)
    
    # doing the same for purchases stats
    # -1 means null 
    
    purchases_list = [[],[],[],[]] # a list of 4 empty lists

    for k in df['purchases']:
        # Only "I have it" has 'v'. Split on v, get the index, return the part of string where number is, regex and int on it
        if 'have' in k:
            purchases_list[0].append( int( re.sub("[^0-9]","",k[k.index('v')+7: k.index('v')+15]) ) )
        else:
            purchases_list[0].append(-1)

        if 'had' in k:
            purchases_list[1].append( int( re.sub("[^0-9]","",k[k.index('d')+6: k.index('d')+13]) ) )
        else:
            purchases_list[1].append(-1)

        # Only 'want' has 'w' in it. Split on w, get the index, return the part of string where number is, regex and int on it
        if 'want' in k:
            purchases_list[2].append( int( re.sub("[^0-9]","",k[k.index('w')+10: k.index('w')+15]) ) )
        else:
            purchases_list[2].append(-1)

        if 'signature' in k:
            purchases_list[3].append( int( re.sub("[^0-9]","",k[k.index('r'): k.index('r')+len(k)-1]) ) )
        else:
            purchases_list[3].append(-1)
            
    purchases_df = pd.DataFrame(purchases_list).T
    purchases_df.columns = [f"{i}" for i in ['have_it', 'had_it', 'want_it', 'my_signature']]
    df = pd.concat([df.drop('purchases', axis = 1), purchases_df], axis = 1, sort = False)
            
    # doing the same for opinions
    opinions = [[],[],[],[],[],[],[],[]] # an empty list of 8 empty lists
    
    for k in df['opinions']:
        if k != "not found": # nulls are coded as "Another Format"
            for pos in range(8):
                opinions[pos].append(int( re.sub("[^0-9]","" ,k.split(')')[pos]) ))
        else:
            for pos in range(8):
                opinions[pos].append(-1)
            
    
    opinions_df = pd.DataFrame(opinions).T
    opinions_df.columns = [f"{i}" for i in ['love_it', 'like_it', 'dislike_it', 'spring', 'summer', 'fall', 'day', 'night']]
    df = pd.concat([df.drop('opinions', axis = 1), opinions_df], axis = 1, sort = False)

    return df

In [248]:
df = clean_up_perfume_df(df)

In [249]:
pd.set_option('max_columns', 100)

In [250]:
print(df.shape)
df.head(2)

(4478, 33)

,perfume_name,designer,group,main_accords,all_notes,top_notes,middle_notes,base_notes,synopsis,overall_rating,total_num_voters,gender,longvity_poor,longvity_weak,longvity_moderate,longvity_long_lasting,longvity_very_long_lasting,sillage_soft,sillage_moderate,sillage_heavy,sillage_enormous,have_it,had_it,want_it,my_signature,love_it,like_it,dislike_it,spring,summer,fall,day,night
0,Eau de Soleil Blanc Tom Ford for women and men,Tom Ford,Oriental Floral,"[('citrus', ' 130'), ('white floral', ' 119'),...","['Bitter Orange', 'Bergamot', 'Petitgrain', 'C...","['Bitter Orange', 'Bergamot', 'Petitgrain', 'C...","['Tunisian Orange Blossom', 'Jasmine', 'Tubero...","['Coconut', 'Amber', 'Vanilla', 'Tonka Bean', ...",Eau De Soleil Blanc\n \n ...,4.11,410.0,women and men,14,25,35,14,12,47,34,20,31,279,40,272,3,100,74,26,3,20,54,5,56
1,Narciso Rodriguez for Him Narciso Rodriguez fo...,Narciso Rodriguez,Aromatic Fougere,"[('ozonic', ' 130'), ('musky', ' 120'), ('patc...","['Violet Leaf', 'Patchouli', 'Amber', 'Musk']",not found,not found,not found,The male fragrance from Narciso Rodriguez and ...,3.94,2311.0,Him Narciso Rodriguez,33,39,173,402,97,87,285,366,111,2021,638,1252,64,100,70,37,55,41,12,58,41

In [286]:
# each 'main_accords' is a long string of a list of tuples. eg.
df['main_accords'][0]

"[('citrus', ' 130'), ('white floral', ' 119'), ('coconut', ' 80'), ('sweet', ' 78'), ('aromatic', ' 52'), ('tuberose', ' 51')]"

In [287]:
main_accords_df['main_accords'][449]

{'red fruits': 130}

<span style='color:navy'> At this moment, all numerical null values are encoded as -1 <br />
The `'main_accords'` column is important in out analysis. Next, extracting the notes of all the perfumes, making them into unique columns, put the concentration of each note under the corresponding columns; for each perfume. <br />
For faster handling, we are going to create a separate data frame, them merge results with the oringinal data frame. <br />
This whole thing, is done in three steps.
</span>

In [288]:
# Extracting Main Accords as Columns:
# split at ), then at ,

# make a df called main_accords_df contains all notes (unique) of any and all perfumes
def accords_df(df):
    
    # fill the nulls is taking care of in the cleaning up function cleaclean_up_perfume_df() 
    
    import re
    # Step 1: Make a set of all possible (repeated once) notes in the whole data frame.
    #--------
    first_split = [] # a list of lists

    for k in df['main_accords']:
        first_split.append(k.split('),'))

    notes = []
    for k in first_split:
        for i in k:
            notes.append(re.sub("[^a-z]"," ", i.split(',')[0].lower()).strip())

    notes = list(set(notes)) # unique now
    
    
    # Step 2: Make a dataframe of these columns (this set), and append it to the original df.
    #--------
    # first create an array of zeros to match the original df rows, and same columns as the notes
    # to fill the temporary notes dataframe with it
    import numpy as np

    notes_df = pd.DataFrame(np.zeros((df.shape[0], len(notes))), 
                            columns = notes)

    # Add the main_accords column to the empty data frame of notes 
    main_accords_df = pd.concat([df['main_accords'], notes_df], axis = 1, sort = False)
    
    return main_accords_df

In [289]:
main_accords_df = accords_df(df)

In [290]:
print(main_accords_df.shape)
main_accords_df.head(2)

(4478, 73)

,main_accords,salty,smoky,,coconut,white floral,fresh spicy,white wine,vanilla,warm spicy,whiskey,ginger,conifer,caramel,woody,vinyl,tropical,musk,fruity,coca cola,powdery,floral,aromatic,milky,yellow floral,nutty,cacao,aquatic,camphor,red fruits,sweet,oud,almond,animalic,gourmand,rum,sand,citrus,beeswax,musky,watery,soft spicy,vodka,tobacco,fresh,tonka coumarin,savory,violet,aldehydic,rose,terpenic,cinnamon,tuberose,sour,cherry,lactonic,herbal,narcotic,ozonic,patchouli,leather,woodsy notes,not found,honey,soapy,metallic,green,bitter,balsamic,marine,earthy,amber,coffee
0,"[('citrus', ' 130'), ('white floral', ' 119'),...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"[('ozonic', ' 130'), ('musky', ' 120'), ('patc...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [291]:
# Step 3: Test if a note exists in main_accords, add its value to the corresponding column in the dataframe.
#--------

# first make a mini dictionary for each perfume of the main accords. Since notes don't repeat in any one perfume
def accords_to_dict(x):
    """
    Returns a dictionary of the notes as keys, and their values as the dictionary values. 
    Can be applied to each row in df['main_accords'] like this: 
    df['main_accords'].map(lambda x: accords_to_dict(x))
    or like this: 
    accords_to_dict(df['main_accords'][row_number]) # this will return the dictionary right away
    
    Parameters:
    -----------
    x: The string text of 'main_accords'
    
    """
    import re
    
    local_notes = []
    local_values = []
    
    if x != 'not found' and ')' in x: # for example, lines 328 and 449 has only one note, with no concentration. 
        lst = x.split('),')

        for k in lst:
            local_notes.append(re.sub("[^a-z]"," ", k.split(',')[0].lower()).strip())
            local_values.append((re.sub("[^0-9]","", k.split(',')[1])))

        local_dict = dict(zip(local_notes, local_values))
        
    elif x != 'not found' and ')' not in x: 
        
        local_dict = {re.sub("[^a-z]"," ", x.lower()).strip() : 130}

    else:
        local_dict = 'not found'
    
    return local_dict

In [292]:
main_accords_df.loc[main_accords_df['main_accords']=='not found',:].shape # we have 40 missing values

(40, 73)

In [293]:
# changing the 'main_accords' column to dictionaries
main_accords_df['main_accords'] = main_accords_df['main_accords'].map(lambda x: accords_to_dict(x))

In [294]:
main_accords_df.head(2)

,main_accords,salty,smoky,,coconut,white floral,fresh spicy,white wine,vanilla,warm spicy,whiskey,ginger,conifer,caramel,woody,vinyl,tropical,musk,fruity,coca cola,powdery,floral,aromatic,milky,yellow floral,nutty,cacao,aquatic,camphor,red fruits,sweet,oud,almond,animalic,gourmand,rum,sand,citrus,beeswax,musky,watery,soft spicy,vodka,tobacco,fresh,tonka coumarin,savory,violet,aldehydic,rose,terpenic,cinnamon,tuberose,sour,cherry,lactonic,herbal,narcotic,ozonic,patchouli,leather,woodsy notes,not found,honey,soapy,metallic,green,bitter,balsamic,marine,earthy,amber,coffee
0,"{'citrus': '130', 'white floral': '119', 'coco...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"{'ozonic': '130', 'musky': '120', 'patchouli':...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<span style='color:navy'> To apply step 3, we need a function to fill in the values from each dictionary to the corresponding columns. </span>

In [295]:
# For every row; put the value of the note in the corresponding column

# 1. make a function 
def fill_in_values(x, df = main_accords_df):
    """
    Extract the values of the dictionary of the accords, and puts these values in the correponding column for the note.
    
    Apply it to the 'main_accords' column in main_accords_df AFTER applying the accords_to_dict() function!
    
    Parameters:
    ----------
    x: 
        The dictionary in the main_accords_df['main_accords']
    df: 
        The data frame for which the above applies, it's main_accords_df by default. 
    """
    row_number = df.loc[df['main_accords'] == x, :].index[0] # row number of that x
    
    if x != 'not found':
        for k in x.keys():
            df[k][row_number] = x[k] # the column having same name as dict key (note), of that row, if filled with the value
                                                         # recall dict[key] gives the value of that key
    
#     return None  # if no return statement, None is assumed.

In [296]:
from time import time
t0 = time()
# 2. apply the fill_in_values() function. 
# It will take long timedd to execute, even on 466 x 57
main_accords_df['main_accords'].map(lambda x: fill_in_values(x));
# don't worry about the warning, it will apply anyway.
print(round((time() - t0) / 60, 2))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

83.2

In [297]:
# Combining the two dataframes: main_accords_df with original df
df = pd.concat([df.drop('main_accords', axis = 1), main_accords_df], axis = 1, sort = False)

In [298]:
df.shape

(4478, 105)

In [302]:
# saving the results
df.to_csv('./data/perfumes_df_ready.csv', index = False)